/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.jvv.openapi.dal.entity;

import com.jvv.openapi.facade.constants.enums.MerchantStatusEnum;
import com.jvv.openapi.facade.constants.enums.PromptTypeEnum;

import java.util.Date;




/**
 * A data object class directly models database table <tt>merchant</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/merchant.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class MerchantDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 公共密钥KEY
	*/
	protected String partnerId;
	/**
	 * 商户名称
	*/
	protected String merchantName;
	/**
	 * 安全校验码
	*/
	protected String securityCode;
	/**
	 * 商户状态
	*/
	protected MerchantStatusEnum status;
	/**
	 * 生效时间
	*/
	protected Date activeTime;
	/**
	 * 过期时间
	*/
	protected Date effectiveTime;
	/**
	 * 错误提示方式
	*/
	protected PromptTypeEnum promptType;

	//========== getters and setters ==========
    /**
     * 返回 公共密钥KEY
     */
	public String getPartnerId() {
		return partnerId;
	}

	/**
	 * 设置 公共密钥KEY
     */
	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
    }
    /**
     * 返回 商户名称
     */
	public String getMerchantName() {
		return merchantName;
	}

	/**
	 * 设置 商户名称
     */
	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
    }
    /**
     * 返回 安全校验码
     */
	public String getSecurityCode() {
		return securityCode;
	}

	/**
	 * 设置 安全校验码
     */
	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
    }
    /**
     * 返回 商户状态
     */
	public MerchantStatusEnum getStatus() {
		return status;
	}

	/**
	 * 设置 商户状态
     */
	public void setStatus(MerchantStatusEnum status) {
		this.status = status;
    }
    /**
     * 返回 生效时间
     */
	public Date getActiveTime() {
		return activeTime;
	}

	/**
	 * 设置 生效时间
     */
	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
    }
    /**
     * 返回 过期时间
     */
	public Date getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * 设置 过期时间
     */
	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
    }
    /**
     * 返回 错误提示方式
     */
	public PromptTypeEnum getPromptType() {
		return promptType;
	}

	/**
	 * 设置 错误提示方式
     */
	public void setPromptType(PromptTypeEnum promptType) {
		this.promptType = promptType;
    }

}
