/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.jvv.openapi.dal.entity;

import java.util.Date;
import com.jvv.openapi.facade.constants.enums.Status;




/**
 * A data object class directly models database table <tt>order_info</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/order_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class OrderInfoDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 全局统一的会话ID
	*/
	protected String gid;
	/**
	 * 序列号
	*/
	protected String serialNo;
	/**
	 * 服务名称
	*/
	protected String serviceName;
	/**
	 * 服务版本
	*/
	protected String serviceVersion;
	/**
	 * 商户ID
	*/
	protected String partnerId;
	/**
	 * 订单状态
	*/
	protected Status status;
	/**
	 * 交易时间
	*/
	protected Date tradeDate;
	/**
	 * 商户订单号
	*/
	protected String merchantOrderNo;
	/**
	 * 请求参数
	*/
	protected String requestParams;
	/**
	 * 结果码
	*/
	protected String resultCode;
	/**
	 * 结果信息
	*/
	protected String resultMessage;

	//========== getters and setters ==========
    /**
     * 返回 全局统一的会话ID
     */
	public String getGid() {
		return gid;
	}

	/**
	 * 设置 全局统一的会话ID
     */
	public void setGid(String gid) {
		this.gid = gid;
    }
    /**
     * 返回 序列号
     */
	public String getSerialNo() {
		return serialNo;
	}

	/**
	 * 设置 序列号
     */
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
    }
    /**
     * 返回 服务名称
     */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * 设置 服务名称
     */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
    }
    /**
     * 返回 服务版本
     */
	public String getServiceVersion() {
		return serviceVersion;
	}

	/**
	 * 设置 服务版本
     */
	public void setServiceVersion(String serviceVersion) {
		this.serviceVersion = serviceVersion;
    }
    /**
     * 返回 商户ID
     */
	public String getPartnerId() {
		return partnerId;
	}

	/**
	 * 设置 商户ID
     */
	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
    }
    /**
     * 返回 订单状态
     */
	public Status getStatus() {
		return status;
	}

	/**
	 * 设置 订单状态
     */
	public void setStatus(Status status) {
		this.status = status;
    }
    /**
     * 返回 交易时间
     */
	public Date getTradeDate() {
		return tradeDate;
	}

	/**
	 * 设置 交易时间
     */
	public void setTradeDate(Date tradeDate) {
		this.tradeDate = tradeDate;
    }
    /**
     * 返回 商户订单号
     */
	public String getMerchantOrderNo() {
		return merchantOrderNo;
	}

	/**
	 * 设置 商户订单号
     */
	public void setMerchantOrderNo(String merchantOrderNo) {
		this.merchantOrderNo = merchantOrderNo;
    }
    /**
     * 返回 请求参数
     */
	public String getRequestParams() {
		return requestParams;
	}

	/**
	 * 设置 请求参数
     */
	public void setRequestParams(String requestParams) {
		this.requestParams = requestParams;
    }
    /**
     * 返回 结果码
     */
	public String getResultCode() {
		return resultCode;
	}

	/**
	 * 设置 结果码
     */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
    }
    /**
     * 返回 结果信息
     */
	public String getResultMessage() {
		return resultMessage;
	}

	/**
	 * 设置 结果信息
     */
	public void setResultMessage(String resultMessage) {
		this.resultMessage = resultMessage;
    }

}
